pipeline {	
	agent {
		docker {
			image 'python'
		}
	}
    stages {	
        stage('Build') {	
            steps {
		sh 'uname -a'
                sh 'python --version'
            }	
        }			
    }
    post {
        always {
            emailext (
                subject: '$DEFAULT_SUBJECT',
                body: '$DEFAULT_CONTENT',
                to: '$DEFAULT_RECIPIENTS',
                attachLog: true
            )
        }
    }
}
